Sprint 1/step 1
sergimax/react-vite-ts-starter pull request #1
Opened 2024-12-18 21:26 UTC by sergimax

2024-12-21 15:44 UTC, SergeyK2004 requested changes
Здравствуйте. 

Вы проделали большую работу, что мне понравилось:

Хорошо выполнена верстка
Тип ингредиента вынесен в отдельный тип, чтобы не дублировать его в разных компонентах
Использование пустого массива зависимостей [] в useEffect 
Использование атрибута key.

но есть некоторые недочеты:

* app.css и app.tsx нужно перенести в отдельную папку и сделать app.css модулем app.module.css, а в компоненте использовать модульные классы, а не строки
* https://disk.yandex.ru/d/s54x2CXEU8rVoA Обратите внимание, что вся страница бургерной не должна скролиться, она должна вся помещаться на экране, на котором ее открывают.
* https://disk.yandex.ru/d/xjglZThnYeK6hw Отображение активных и не активных пунктов меню отличаются, сверьтесь с макетом.
* Инлайн-стилей style={{не должно быть в проекте, если они не меняются динамически в коде компонента. Это затрудняет управление стилями. Все стили описываются в модульных .module.css файлах, а в коде компонентов используются модульные css-стили.

Исправьте указанные недочеты и присылайте работу на повторную проверку.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-content/app-content.tsx
> +        setChosenBunsId('60666c42cc7b410027a1a9b1');
Надо исправить:
Не стоит харкордить id ингредиентов. Приложение не должно быть привязано к конкретным id. Уже во творой части этой ПР вам нужно будет загрузить массив с сервера и вы не можете знать, какие id будут там у ингредиентов. В таком случае придется переписывать приложение, что недопустимо.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-content/app-content.tsx
> +    const ActiveBlocks = [
Надо исправить:

Создание подобного массива некорректно, так как его элементы абсолютно различны. Необходимо непосредственно в рендере прописать вывод двух компонентов, один из которыз отвечает за список ингредиентов (левую часть сайта), второй за конструктор (правую часть)
У каждого из них свой функционал и свой набор пропсов. Массив ингредиентов у каждого тоже будет свой. Сейчас вы используете один и тот-же массив только для отработки и проверки верстки.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-content/app-content.tsx
> +    }, []);
Отлично:
Хорошо, что указываете корректный массив зависимостей у хука.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-content/app-content.tsx
> +                        key={index}
Можно лучше:
Обратите внимание, что индекс элемента в массиве это самый нежелательный вариант значений для key.
Например в конструкторе есть функционал перетаскивания элементов и индекс у элементов будет изменяться, но Реакт этого не поймет и отображение элементов станет некорректным.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-header/app-header.tsx
> +    const leftMenuItems = [
Можно лучше:
Пункты навигационного меню не являются динамически изменяемыми и создавать из них массив не очень удачная идея.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-header/app-header.tsx
> +            <nav className={styles.navigation}>
Отлично:
Хорошо, что используете корректные теги для элементов сайта

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-header/app-header.tsx
> +                        <MenuButton
Можно лучше:
Обратите внимание, что пункты меню это ссылки, можно на данном этапе использовать тег <a> который в последствии вы замените на соответствующий компонент, когда будете реализовывать роутинг в приложении.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.tsx
> +    const [chosenIngredientsData, setIngredientsData] = useState<
Можно лучше:

Данные об ингредиентах в конструкторе было бы лучше хранить в объекте, в котором будет два поля

{
bun: Ingredient | null
ingredients: Ingredient[]
}

Тогда вы всегда сохраняете выбранную булку в отдельном свойстве, а все остальные ингредиенты в массиве.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/burger-ingredients/types.ts
> +export type Ingredient = {
Надо исправить:
Те типы, которые используются не только в текущем компоненте, нужно вынести в отдельную папку types, которая будет общей для всего проекта и в там описать интерфейсы данных, используемых в разных компонентов

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.tsx
> +            const ingredientList = [...sauseList, ...mainList];
Можно лучше:
Необходимо исключить пересортировку элементов в массиве конструткора. Порядок добавления ингредентов важен, его необходимо сохранять.

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.tsx
> +                style={{
Надо исправить:
Инлайн стилей не должно быть, их нужно перенести в модуль

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/burger-ingredients-category/burger-ingredients-category.tsx
> +                    return <Ingredient data={element} key={index}/>
Отлично:
Хорошо, что при выводе каждого массива вы не забывает про key

2024-12-21 15:44 UTC, SergeyK2004 commented on src/components/app-content/app-content.tsx
> +            content: <BurgerIngredients ingredients={ingredients} />,
Вам нужно указать тег section внутри BurgerIngredients и BurgerConstructor, чтобы код стал семантически правильным. И это очистит код  от лишних несемантических div

Это могло бы выглядеть в app вот таким образом:

```jsx
  return (
    <>
      <AppHeader />
      <main className={appStyles.row}>
        <BurgerIngredients tabs={Tabs} data={Data} />
        <BurgerConstructor data={Data} />
      </main>
    </>
  );
```

2024-12-21 19:41 UTC, sergimax commented on src/components/app-content/app-content.tsx
> +        setChosenBunsId('60666c42cc7b410027a1a9b1');
Понял, исходил из необходимости предоставить на проверку вариант верстки с уже имеющимися данными для отображения

2024-12-21 20:10 UTC, sergimax commented on src/components/app-header/app-header.tsx
> +    const leftMenuItems = [
вынес элементы из массива

2024-12-21 20:11 UTC, sergimax commented on src/components/app-content/app-content.tsx
> +                        key={index}
массив упразднён, вместе с ним и необходимость выдачи key

2024-12-21 20:11 UTC, sergimax commented on src/components/app-content/app-content.tsx
> +    const ActiveBlocks = [
вынес элементы из массива

2024-12-21 20:13 UTC, sergimax commented on src/components/app-header/app-header.tsx
> +                        <MenuButton
убрал `MenuButton`, содержимое вынес в компонент

2024-12-21 20:51 UTC, sergimax commented on src/components/burger-ingredients/types.ts
> +export type Ingredient = {
вынес неуникальные типы в общую директорию `types`

2024-12-21 22:27 UTC, sergimax commented on src/components/burger-constructor/burger-constructor.tsx
> +            const ingredientList = [...sauseList, ...mainList];
упразднил данную логику, вывел определение списка используемых ингредиентов на уровень выше в компонент `AppContent`

2024-12-21 22:45 UTC, sergimax commented on src/components/app-content/app-content.tsx
> +            content: <BurgerIngredients ingredients={ingredients} />,
убраны компоненты `AppContent`, `AppContentBlock`

2024-12-22 12:38 UTC, sergimax commented
Переработал верстку по требованиям

2024-12-22 22:23 UTC, SergeyK2004 approved these changes
Отличная работа! Выглядит очень круто! Вы прекрасно постарались. Код выглядит аккуратно, хорошо сделана верстка и статический вид страницы. Теперь необходимо ее оживить. Предварительная итерация принята. Теперь вам нужно сделать некоторые изменения (добавить модальные окна).

2024-12-22 22:23 UTC, SergeyK2004 commented on src/components/app/app.tsx
> +            </main>
👍

2024-12-23 08:45 UTC, merged