Sprint 1/step 2
sergimax/react-vite-ts-starter pull request #3
Opened 2024-12-24 21:04 UTC by sergimax

Пункты задания:
- [x] Функциональные компоненты
- [ ] Подключитесь к API
- [ ] Компоненты главной страницы: `Modal` и `ModalOverlay`
- [ ] Компоненты содержимого модальных окон: `IngredientDetails` и `OrderDetails`
- [x] Типизация

2024-12-28 11:36 UTC, SergeyK2004 requested changes
Отличная работа. Очень хорошо выполнена работа с порталом. Функционал реализован, но есть небольшое замечание по формированию контента модальных окон. Посмотрите их в коде.

Можно лучше:

* Хорошо, если при наведении на ингредиент, мышка будет принимать значение pointer, чтобы пользователь сразу понимал, что ингредиент является интерактивным элементов.
* При клике в табы хорошо будет скролить ингредиенты до выбранной в Табе группы.

2024-12-28 11:36 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.tsx
> +                                <OrderDetails orderId={DEFAULT_ORDER_ID} />
Надо исправить.
Не совсем корректно формировать здесь разметку с использованием другого компонента. Так возникает высокая связанность между компонентами. будет корректнее передавать в обработчик выбранный ингредиент или необходимые данные заказа, а уже разметка с использованием других компонентов будет формироваться за пределами этого компонента.

Надо исправить здесь и в выводе модального окна ингредиента

2024-12-29 14:46 UTC, sergimax commented on src/components/burger-constructor/burger-constructor.tsx
> +                                <OrderDetails orderId={DEFAULT_ORDER_ID} />
- добавил смену курсора при наведении на интерактивные элементы
- добавил скролл по клику на категорию ингредиента
- вынес формирование содержимого модального окна выше - в `app`
- сделал сортировку импортов

2024-12-30 03:46 UTC, SergeyK2004 approved these changes
Отличная работа.
Ваш проект принят. 
Поздравляю со сдачей и с наступающем Новым Годом.

2024-12-30 09:58 UTC, merged